/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import Controle.Controle;
import modelo.Protocolo;
import java.util.Timer;
import java.util.TimerTask;
import modelo.Estaticos;
import modelo.Precipitacao;
import modelo.Temperatura;
import modelo.Umidade;

/**
 *
 * @author Rever
 */
public class frmPrincipal extends javax.swing.JDialog
{

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblumidTempoReal = new javax.swing.JLabel();
        lblUmidadeTempoReal = new javax.swing.JLabel();
        lblTempTempoReal = new javax.swing.JLabel();
        lblTemperaturaTempoReal = new javax.swing.JLabel();
        lblPrecTempoReal = new javax.swing.JLabel();
        lblPrecipitacaoTempoReal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblUmidBD = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUmidadeBD = new javax.swing.JLabel();
        lblTempBD = new javax.swing.JLabel();
        lblTemperaturaBD = new javax.swing.JLabel();
        lblPrecBD = new javax.swing.JLabel();
        lblPrecipitacaoBD = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jLabel7.setText("jLabel7");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        lblumidTempoReal.setText("Umidade");

        lblUmidadeTempoReal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblUmidadeTempoReal.setText("Umidade");

        lblTempTempoReal.setText("Temperatura");

        lblTemperaturaTempoReal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTemperaturaTempoReal.setText("Temperatura");

        lblPrecTempoReal.setText("Precipitação");

        lblPrecipitacaoTempoReal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblPrecipitacaoTempoReal.setText("Precipitação");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Tempo Real");

        lblUmidBD.setText("Umidade");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Banco de Dados");

        lblUmidadeBD.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblUmidadeBD.setText("Umidade");

        lblTempBD.setText("Temperatura");

        lblTemperaturaBD.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTemperaturaBD.setText("Temperatura");

        lblPrecBD.setText("Precipitação");

        lblPrecipitacaoBD.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblPrecipitacaoBD.setText("Precipitação");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecTempoReal)
                            .addComponent(lblTemperaturaTempoReal)
                            .addComponent(lblTempTempoReal)
                            .addComponent(lblUmidadeTempoReal)
                            .addComponent(lblumidTempoReal)
                            .addComponent(lblPrecipitacaoTempoReal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUmidBD)
                            .addComponent(lblPrecipitacaoBD)
                            .addComponent(lblPrecBD)
                            .addComponent(lblTemperaturaBD)
                            .addComponent(lblTempBD)
                            .addComponent(lblUmidadeBD))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblumidTempoReal)
                    .addComponent(lblUmidBD))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUmidadeTempoReal)
                        .addGap(18, 18, 18)
                        .addComponent(lblTempTempoReal)
                        .addGap(18, 18, 18)
                        .addComponent(lblTemperaturaTempoReal)
                        .addGap(18, 18, 18)
                        .addComponent(lblPrecTempoReal)
                        .addGap(18, 18, 18)
                        .addComponent(lblPrecipitacaoTempoReal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUmidadeBD)
                        .addGap(18, 18, 18)
                        .addComponent(lblTempBD)
                        .addGap(18, 18, 18)
                        .addComponent(lblTemperaturaBD)
                        .addGap(18, 18, 18)
                        .addComponent(lblPrecBD)
                        .addGap(18, 18, 18)
                        .addComponent(lblPrecipitacaoBD)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        Controle controle = new Controle();
        Umidade umidade = new Umidade();
        Temperatura temperatura = new Temperatura();
        Precipitacao precipitacao = new Precipitacao();                
        Timer timer = new Timer();
        TimerTask task = new TimerTask()
        {
            @Override
            public void run()
            {
                controle.cadastrarPrecipitacao();
                controle.cadastrarTemperatura();
                controle.cadastrarUmidade();

                lblUmidadeTempoReal.setText(Protocolo.umidade + "%");
                lblTemperaturaTempoReal.setText(Protocolo.temperatura + "ºC");
                lblPrecipitacaoTempoReal.setText(Protocolo.precipitacao);

                lblUmidadeBD.setText(String.valueOf(umidade.getValorUmidade() + "%"));
                lblTemperaturaBD.setText(String.valueOf(temperatura.getValorTemperatura() + "ºC"));
                lblPrecipitacaoBD.setText(String.valueOf(precipitacao.getValorPrecipitacao()));

            }
        };
        timer.schedule(task, 0, 1000);


    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmPrincipal dialog = new frmPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblPrecBD;
    private javax.swing.JLabel lblPrecTempoReal;
    private javax.swing.JLabel lblPrecipitacaoBD;
    private javax.swing.JLabel lblPrecipitacaoTempoReal;
    private javax.swing.JLabel lblTempBD;
    private javax.swing.JLabel lblTempTempoReal;
    private javax.swing.JLabel lblTemperaturaBD;
    private javax.swing.JLabel lblTemperaturaTempoReal;
    private javax.swing.JLabel lblUmidBD;
    private javax.swing.JLabel lblUmidadeBD;
    private javax.swing.JLabel lblUmidadeTempoReal;
    private javax.swing.JLabel lblumidTempoReal;
    // End of variables declaration//GEN-END:variables
}
